### ISSUE TITLE
Cuidado con la Excepciones

### ISSUE THREAD

**Issue by jmcrispino** [UnlamHalcones/Zork#13]
https://github.com/UnlamHalcones/Zork/blob/939fc23d4fef726c0ae5a8e8caf6391c14038658/test/ar/edu/unlam/halcones/entities/LocationTests.java#L16

Si un objeto por lo que se ve arroja una Exception, fijarse si se puede inicializar al inicio. 
El Test debería fallar por lo prueba en si misma y no por una Exception.

**Comment by NicolasCailotto** [comment]
Fixeado
