### ISSUE TITLE
Nombres de Test

### ISSUE THREAD

**Issue by jmcrispino** [UnlamHalcones/Zork#14]
https://github.com/UnlamHalcones/Zork/blob/939fc23d4fef726c0ae5a8e8caf6391c14038658/test/ar/edu/unlam/halcones/entities/PlaceTests.java#L23

El nombre de Test debe ser lo más representativo posible de lo que estoy testeando y que refleje lo que se prueba. Quizas en este se podría cambiar a queExistaItem ya que el test no devuelve nada (void) El test se realiza por Assert.

**Comment by NicolasCailotto** [comment]
Fixeado
